import Foundation

// Caches rendered List items so the JS renderItem only runs when the items or
// renderItemId change - mirroring Android's ListRenderer, which renders items in
// LaunchedEffect(rawItems, renderItemId) and reuses the result otherwise. Keyed
// by renderItemId; the cached items are deep-compared to detect changes. Cleared
// on each bundle load (renderItemIds are regenerated by render()).
@MainActor
final class ListCache {
    static let shared = ListCache()

    private struct Entry {
        let items: NSArray
        let rendered: [String]
    }
    private var entries: [String: Entry] = [:]

    func rendered(renderItemId: String, items: [Any]) -> [String] {
        let key = items as NSArray
        if let entry = entries[renderItemId], entry.items.isEqual(key) {
            return entry.rendered // unchanged - no JS work
        }
        let result = items.enumerated().compactMap { index, item in
            RuntimeBridge.shared.renderListItem(renderItemId, jsonLiteral(item), index)
        }
        entries[renderItemId] = Entry(items: key, rendered: result)
        return result
    }

    func clear() { entries.removeAll() }

    private func jsonLiteral(_ item: Any) -> String {
        if JSONSerialization.isValidJSONObject(item),
           let data = try? JSONSerialization.data(withJSONObject: item),
           let s = String(data: data, encoding: .utf8) {
            return s
        }
        if let s = item as? String {
            let escaped = s
                .replacingOccurrences(of: "\\", with: "\\\\")
                .replacingOccurrences(of: "\"", with: "\\\"")
            return "\"\(escaped)\""
        }
        if let n = item as? NSNumber { return n.stringValue }
        return "null"
    }
}
